{% set version = "3.2.1" %}

package:
    name: pyamg
    version: {{ version }}

source:
    fn: pyamg-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/p/pyamg/pyamg-{{ version }}.tar.gz
    md5: a766393c628c29696d31b3dbbdb6e008

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - python
        - numpy x.x
        - zlib  # [linux]
    run:
        - python
        - numpy x.x
        - scipy
        - zlib  # [linux]

test:
    requires:
        - nose
    imports:
        - pyamg

about:
    home: http://www.pyamg.org/
    license: MIT
    license_file: LICENSE.txt
    summary: "Algebraic Multigrid Solvers in Python"

extra:
  recipe-maintainers:
    - jakevdp
